name: Get Last Alert Robot run2

on:
  push:
    branches:
      - main

jobs:
  get_last_git_action_run:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
    - name: Checkout Step
      uses: actions/checkout@v3
    - name: Install Flask
      run: pip install flask
    - name: Get last git action run
      run: |
       pip install requests
       python get_git_action_results.py
